all: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
1: vc.java
	javac -d . vc.java
2: comment1.vc
	java VC.vc comment1.vc > comment1.s
	diff comment1.s comment1.sol
3: comment2.vc
	java VC.vc comment2.vc > comment2.s
	diff comment2.s comment2.sol
4: comment3.vc
	java VC.vc comment3.vc > comment3.s
	diff comment3.s comment3.sol
5: comment4.vc
	java VC.vc comment4.vc > comment4.s
	diff comment4.s comment4.sol
6: error1.vc
	java VC.vc error1.vc > error1.s
	diff error1.sol error1.s
7: error2.vc
	java VC.vc error2.vc > error2.s
	diff error2.sol error2.s
8: error3.vc
	java VC.vc error3.vc > error3.s
	diff error3.sol error3.s
9: error4.vc
	java VC.vc error4.vc > error4.s
	diff error4.sol error4.s
10: escape.vc
	java VC.vc escape.vc > escape.s
	diff escape.sol escape.s
11: fib.vc
	java VC.vc fib.vc > fib.s
	diff fib.sol fib.s
12: gcd.vc
	java VC.vc gcd.vc > gcd.s
	diff gcd.sol gcd.s
13: longestmatch.vc
	java VC.vc longestmatch.vc > longestmatch.s
	diff longestmatch.sol longestmatch.s
14: string.vc
	java VC.vc string.vc > string.s
	diff string.sol string.s
15: tab.vc
	java VC.vc tab.vc > tab.s
	diff tab.sol tab.s
16: tokens.vc
	java VC.vc tokens.vc > tokens.s
	diff tokens.sol tokens.s
